language: php

branches:
  only:
  - master

matrix:
  include:
  - os: linux
    php: 7.1
  - os: osx
    php: 7.2
  - os: windows
    php: 7.2

install:
  - travis_retry composer install --no-interaction

script: vendor/bin/phpunit -v
